# Displays
CONFIG_ZMK_DISPLAY=y

# Extend Range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Name
CONFIG_ZMK_KEYBOARD_NAME="zings-corne-v2"

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10